#!/usr/bin/env ruby
require 'rubygems'
require "daemons"
require "daemons/rails/config"

config = Daemons::Rails::Config.new("suppress_timer", File.dirname(__FILE__) + "/../../")

Daemons.run File.dirname(__FILE__) + "/suppress_timer.rb", config.to_hash